modLoader="lowcodefml"
loaderVersion="[1,)"
license="ARR"
showAsResourcePack=false
showAsDataPack=true

[[mods]]
	modId="geophilic"
	version="3.4"
	displayName="Geophilic"
	displayURL="https://modrinth.com/datapack/geophilic"
	logoFile="pack.png"
	authors="bebebea_loste"
	description="A subtle-ish overhaul of vanilla Overworld biomes."

	[[dependencies.geophilic]]
		modId="minecraft"
		mandatory=true
		versionRange="[1.20,)"
		ordering="NONE"
		side="BOTH"